import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve, join } from "node:path";
import { tmpdir } from "node:os";
import { runMigrations } from "../src/storage/migrate.ts";
import { openDb, type DbHandle } from "../src/storage/sqlite.ts";
import { parseDoc } from "../src/vault/parser.ts";
import { upsertDocNodeAndEdges, listEdgesFromFile, countNodes } from "../src/graph/engine.ts";
import {
  createStubExtractorClient,
  extractDecisionsFromDoc,
  classifyDecision,
  materializeDecisions,
  parseExtractorJson,
  type ExtractedDecision,
} from "../src/extractor/index.ts";

function mkWorkspace() {
  const dir = mkdtempSync(resolve(tmpdir(), "orgmem-extractor-"));
  const vault = join(dir, "vault");
  const db = join(dir, "dev.db");
  mkdirSync(vault, { recursive: true });
  return { dir, vault, db };
}

// Seed a Document node directly (mirrors what `kg import` would do on one file).
function seedSourceDoc(
  handle: DbHandle,
  vault: string,
  relPath: string,
  body: string,
  mtime = 1_713_000_000_000, // fixed ms for reproducible date in tests
): string {
  const docDir = join(vault, relPath.split("/").slice(0, -1).join("/"));
  if (docDir !== vault) mkdirSync(docDir, { recursive: true });
  writeFileSync(join(vault, relPath), body, "utf8");
  const parsed = parseDoc({ relPath, raw: body });
  upsertDocNodeAndEdges(handle, relPath, parsed);
  // Overwrite mtime so the derived Decision date is stable across test runs.
  handle.raw.prepare("UPDATE nodes SET mtime = ? WHERE id = ?;").run(mtime, parsed.id);
  return parsed.id;
}

describe("parseExtractorJson", () => {
  test("parses raw JSON", () => {
    const out = parseExtractorJson<{ x: number }>('{"x":1}');
    expect(out.x).toBe(1);
  });
  test("strips ```json fences", () => {
    const out = parseExtractorJson<{ x: string }>('```json\n{"x":"y"}\n```');
    expect(out.x).toBe("y");
  });
  test("salvages from trailing prose", () => {
    const out = parseExtractorJson<{ ok: boolean }>('{"ok":true}\nNote: generated by LLM.');
    expect(out.ok).toBe(true);
  });
  test("throws on unrecoverable input", () => {
    expect(() => parseExtractorJson("not json at all")).toThrow(/parse failed/);
  });
});

describe("classifyDecision", () => {
  test("parses a well-formed classifier response", async () => {
    const client = createStubExtractorClient([
      { match: "<snippet>", text: '{"label":"decision","reasoning":"confirmed"}' },
    ]);
    const result = await classifyDecision(client, "Approach C is CHOSEN.");
    expect(result.label).toBe("decision");
    expect(result.reasoning).toBe("confirmed");
  });
  test("rejects an invalid label", async () => {
    const client = createStubExtractorClient([
      { match: "<snippet>", text: '{"label":"maybe","reasoning":"?"}' },
    ]);
    await expect(classifyDecision(client, "snippet")).rejects.toThrow(/invalid label/);
  });
  test("rejects malformed JSON", async () => {
    const client = createStubExtractorClient([
      { match: "<snippet>", text: "not json" },
    ]);
    await expect(classifyDecision(client, "snippet")).rejects.toThrow(/malformed/);
  });
});

describe("extractDecisionsFromDoc", () => {
  test("normalizes the decisions list + drops empty text", async () => {
    const client = createStubExtractorClient([
      {
        match: "sample doc",
        text: JSON.stringify({
          decisions: [
            { text: "Approach C: CHOSEN", reasoning: "marker", line: 7 },
            { text: "   ", reasoning: "empty", line: null }, // dropped: blank text
            { text: "MVP에서 제외: GUI — 3개월 이후 고려.", reasoning: "scope exclusion", line: 12 },
          ],
        }),
      },
    ]);
    const out = await extractDecisionsFromDoc(client, "sample doc", "body");
    expect(out.length).toBe(2);
    expect(out[0]!.text).toBe("Approach C: CHOSEN");
    expect(out[0]!.line).toBe(7);
    expect(out[1]!.text).toBe("MVP에서 제외: GUI — 3개월 이후 고려.");
  });
  test("rejects non-array decisions field", async () => {
    const client = createStubExtractorClient([
      { match: "sample", text: '{"decisions":"oops"}' },
    ]);
    await expect(extractDecisionsFromDoc(client, "sample", "body")).rejects.toThrow(/non-array/);
  });
  test("rejects malformed JSON", async () => {
    const client = createStubExtractorClient([
      { match: "sample", text: "not json at all" },
    ]);
    await expect(extractDecisionsFromDoc(client, "sample", "body")).rejects.toThrow(/malformed/);
  });
});

describe("materializeDecisions", () => {
  let ws: ReturnType<typeof mkWorkspace>;
  let handle: DbHandle;

  beforeEach(() => {
    ws = mkWorkspace();
    runMigrations(ws.db);
    handle = openDb({ path: ws.db, loadVec: true });
  });
  afterEach(() => {
    handle.raw.close();
    rmSync(ws.dir, { recursive: true, force: true });
  });

  test("creates Decision nodes + decided_in edges under decisions/", () => {
    const sourceId = seedSourceDoc(
      handle,
      ws.vault,
      "docs/design.md",
      `---\nid: document-design\ntype: Document\ntitle: Design\n---\n\n# Design\n\n결정들.\n`,
    );

    const extracted: ExtractedDecision[] = [
      { text: "Approach C: CHOSEN", reasoning: "CHOSEN marker", line: 7 },
      { text: "MVP에서 제외: GUI — 3개월 이후 고려.", reasoning: "scope exclusion", line: 12 },
    ];

    const nodesBefore = countNodes(handle);
    const report = materializeDecisions(handle, ws.vault, sourceId, extracted);

    expect(report.created.length).toBe(2);
    expect(report.skipped.length).toBe(0);
    expect(report.errors.length).toBe(0);

    expect(countNodes(handle)).toBe(nodesBefore + 2);

    for (const c of report.created) {
      expect(c.mdPath.startsWith("decisions/")).toBe(true);
      expect(c.mdPath.endsWith(".md")).toBe(true);
      expect(existsSync(join(ws.vault, c.mdPath))).toBe(true);

      const raw = readFileSync(join(ws.vault, c.mdPath), "utf8");
      const parsed = parseDoc({ relPath: c.mdPath, raw });
      expect(parsed.type).toBe("Decision");
      // single decided_in edge back to the source doc
      expect(parsed.fmEdges.length).toBe(1);
      expect(parsed.fmEdges[0]!.relation).toBe("decided_in");
      expect(parsed.fmEdges[0]!.to).toBe(sourceId);

      // edge row in sqlite
      const edgeRows = listEdgesFromFile(handle, c.mdPath);
      expect(edgeRows.length).toBe(1);
      expect(edgeRows[0]!.relation).toBe("decided_in");
      expect(edgeRows[0]!.dstId).toBe(sourceId);
    }
  });

  test("is idempotent: re-running on the same extraction is a no-op", () => {
    const sourceId = seedSourceDoc(
      handle,
      ws.vault,
      "docs/design.md",
      `---\nid: document-design\ntype: Document\ntitle: Design\n---\n\nbody\n`,
    );
    const extracted: ExtractedDecision[] = [
      { text: "Approach C: CHOSEN", reasoning: "r", line: 7 },
      { text: "MVP에서 제외: GUI", reasoning: "r", line: 12 },
    ];

    const first = materializeDecisions(handle, ws.vault, sourceId, extracted);
    expect(first.created.length).toBe(2);
    expect(first.skipped.length).toBe(0);

    const nodesAfterFirst = countNodes(handle);

    const second = materializeDecisions(handle, ws.vault, sourceId, extracted);
    expect(second.created.length).toBe(0);
    expect(second.skipped.length).toBe(2);
    expect(second.errors.length).toBe(0);

    // no new rows
    expect(countNodes(handle)).toBe(nodesAfterFirst);
    // the skipped entries reference the originally-created mdPaths
    const firstIds = new Set(first.created.map((c) => c.id));
    for (const s of second.skipped) {
      expect(firstIds.has(s.id)).toBe(true);
      expect(s.alreadyPresent).toBe(true);
    }
  });

  test("rejects an unknown source doc", () => {
    expect(() =>
      materializeDecisions(handle, ws.vault, "document-does-not-exist", [
        { text: "x", reasoning: "", line: null },
      ]),
    ).toThrow(/does not exist/);
  });

  test("rejects Person as a source (only Document/Meeting allowed)", () => {
    const sourceId = seedSourceDoc(
      handle,
      ws.vault,
      "people/alice.md",
      `---\nid: person-alice\ntype: Person\ntitle: Alice\n---\n\n# Alice\n`,
    );
    expect(() =>
      materializeDecisions(handle, ws.vault, sourceId, [
        { text: "x", reasoning: "", line: null },
      ]),
    ).toThrow(/expected Document or Meeting/);
  });

  test("records extractor metadata on the Decision frontmatter", () => {
    const sourceId = seedSourceDoc(
      handle,
      ws.vault,
      "docs/plan.md",
      `---\nid: document-plan\ntype: Document\ntitle: Plan\n---\n\nbody\n`,
    );
    const report = materializeDecisions(handle, ws.vault, sourceId, [
      { text: "Locked: temperature=0 for extract path.", reasoning: "reproducibility", line: 42 },
    ]);
    expect(report.created.length).toBe(1);

    const c = report.created[0]!;
    const raw = readFileSync(join(ws.vault, c.mdPath), "utf8");
    const parsed = parseDoc({ relPath: c.mdPath, raw });
    expect(parsed.frontmatter.extractor).toBe("lane-c-v1.1");
    expect(parsed.frontmatter.source_line).toBe(42);
    expect(parsed.frontmatter.extractor_reasoning).toBe("reproducibility");
  });
});
