#!/usr/bin/env bun
/**
 * Generates `src/storage/migrations.generated.ts` — a TypeScript manifest
 * that imports every `.sql` file under `src/storage/migrations/` as a
 * text-string literal via Bun's `with { type: "text" }` import attribute.
 *
 * Why a manifest exists at all:
 *   The runtime migrate.ts originally walked `migrations/` with
 *   `readdirSync()`, which works in dev (`bun src/cli/kg.ts`) but breaks
 *   the moment we ship a `bun build --compile` single binary — bun does
 *   not auto-bundle files only accessed via runtime FS reads, so the
 *   resulting `kg-darwin-arm64` / `kg-linux-x86_64` binaries had no
 *   `migrations/` directory and `kg init` died with
 *     ENOENT: scandir '/$bunfs/root/migrations'
 *
 *   Importing each `.sql` with the `text` attribute forces bun to bundle
 *   the file content as a string literal at compile time. The compiled
 *   binary now carries every migration verbatim, no FS lookup needed.
 *
 * Workflow:
 *   - Adding a new migration → `bun run db:generate` (drizzle-kit emits
 *     SQL) → this script regenerates the manifest → commit both the SQL
 *     and the manifest in one PR.
 *   - The CI 'manifest drift' check (in .github/workflows/ci.yml) runs
 *     this script and asserts `git diff --exit-code` so a forgotten
 *     regeneration fails CI loud rather than reaching prod.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const here = dirname(fileURLToPath(import.meta.url));
const migrationsDir = resolve(here, "..", "src", "storage", "migrations");
const outFile = resolve(here, "..", "src", "storage", "migrations.generated.ts");

const sqlFiles = readdirSync(migrationsDir)
  .filter((f) => f.endsWith(".sql"))
  .sort();

if (sqlFiles.length === 0) {
  console.error(`No .sql migrations found in ${migrationsDir}`);
  process.exit(1);
}

// Hash each file so the manifest can carry sha256 alongside the bytes,
// keeping migrate.ts's checksum-verified `schema_version` invariant.
const entries = sqlFiles.map((f, i) => {
  const sql = readFileSync(resolve(migrationsDir, f), "utf8");
  const checksum = createHash("sha256").update(sql).digest("hex");
  return {
    index: i,
    file: f,
    name: f.replace(/\.sql$/, ""),
    checksum,
    bytes: sql.length,
  };
});

const lines: string[] = [];
lines.push("// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT.");
lines.push("//");
lines.push("// To regenerate after `drizzle-kit generate` adds a new SQL file:");
lines.push("//   bun run db:generate     # runs drizzle-kit + this script");
lines.push("//   bun scripts/gen-migrations-manifest.ts   # standalone");
lines.push("//");
lines.push("// CI verifies this file matches the on-disk SQL (manifest drift check).");
lines.push("");
for (const e of entries) {
  lines.push(`import sql_${e.index} from "./migrations/${e.file}" with { type: "text" };`);
}
lines.push("");
lines.push("export interface EmbeddedMigration {");
lines.push("  /** Stem of the SQL filename, e.g. '0000_curved_lenny_balinger'. */");
lines.push("  name: string;");
lines.push("  /** Raw SQL contents (utf-8). */");
lines.push("  sql: string;");
lines.push("  /** sha256(sql) — duplicated here so build-time + runtime hashes always agree. */");
lines.push("  checksum: string;");
lines.push("}");
lines.push("");
lines.push("export const MIGRATIONS: readonly EmbeddedMigration[] = [");
for (const e of entries) {
  lines.push(`  { name: ${JSON.stringify(e.name)}, sql: sql_${e.index}, checksum: ${JSON.stringify(e.checksum)} },`);
}
lines.push("];");
lines.push("");

writeFileSync(outFile, lines.join("\n"), "utf8");

const totalBytes = entries.reduce((sum, e) => sum + e.bytes, 0);
console.log(
  `wrote ${outFile}\n  (${entries.length} migration${entries.length === 1 ? "" : "s"}, ${totalBytes} bytes of SQL embedded)`,
);
