#!/usr/bin/env bun
/**
 * Generates `src/storage/sqlite-vec-native.generated.ts` — a thin
 * platform-specific wrapper that imports the host's `vec0.<ext>` shared
 * library as a bundled file via Bun's `with { type: "file" }`.
 *
 * Why this exists:
 *   `bun build --compile` does not bundle native shared libraries that
 *   are loaded via dlopen() at runtime (sqlite-vec's loader resolves
 *   `sqlite-vec-<os>-<arch>/vec0.<ext>` via `import.meta.resolve`, which
 *   the compiled binary then can't find — it lives outside the bundled
 *   /$bunfs tree). v0.1.1 shipped binaries that crashed at first
 *   `kg embed/ask/search` with
 *     Cannot find module 'sqlite-vec-darwin-arm64/vec0.dylib'
 *
 *   By marking the .dylib/.so as a `type: "file"` import, bun bundles
 *   its bytes into the binary as an asset. At runtime sqlite.ts
 *   extracts those bytes into ~/.cache/orgmem/sqlite-vec/ (real FS path
 *   that dlopen() can open) and calls `db.loadExtension()` on it.
 *
 * Workflow:
 *   - The committed version of the generated file is a STUB
 *     (BUNDLED_VEC_PATH = null) so `bun test` works on any contributor
 *     machine without regeneration. Runtime sqlite.ts falls back to
 *     `sqliteVec.load()` (the original dev-mode loader) when the path
 *     is null.
 *   - .github/workflows/release.yml runs THIS script on each matrix
 *     runner before `bun build --compile`, so the linux runner emits a
 *     `sqlite-vec-linux-x64/vec0.so` import and the macOS runner emits
 *     a `sqlite-vec-darwin-arm64/vec0.dylib` import. The compiled
 *     binary then carries the right native lib.
 *   - Contributors who want to dogfood `bun build --compile` locally
 *     run `bun scripts/gen-sqlite-vec-native.ts`, test, then
 *     `git checkout -- src/storage/sqlite-vec-native.generated.ts`
 *     to restore the stub before committing.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const outFile = resolve(repoRoot, "src", "storage", "sqlite-vec-native.generated.ts");

const platform = process.platform;
const arch = process.arch;

const SUPPORTED: Record<string, { os: string; ext: string }> = {
  "darwin-arm64": { os: "darwin", ext: "dylib" },
  "darwin-x64": { os: "darwin", ext: "dylib" },
  "linux-arm64": { os: "linux", ext: "so" },
  "linux-x64": { os: "linux", ext: "so" },
  "win32-x64": { os: "windows", ext: "dll" },
};

const key = `${platform}-${arch}`;
const target = SUPPORTED[key];
if (!target) {
  console.error(`unsupported host platform ${key} — sqlite-vec ships no native lib here`);
  process.exit(1);
}

const packageName = `sqlite-vec-${target.os}-${arch}`;
const libFilename = `vec0.${target.ext}`;
const importSpec = `${packageName}/${libFilename}`;

// Hash the live native lib so the runtime cache key changes whenever the
// underlying sqlite-vec build changes. Path resolution mirrors what bun's
// `with { type: "file" }` import would resolve to during build.
const sourcePath = resolve(repoRoot, "node_modules", packageName, libFilename);
let sha = "unknown";
try {
  sha = createHash("sha256").update(readFileSync(sourcePath)).digest("hex");
} catch (err) {
  console.error(`could not hash ${sourcePath}: ${(err as Error).message}`);
  console.error(`run \`bun install\` first so the platform-specific sqlite-vec package is present.`);
  process.exit(1);
}

const lines: string[] = [];
lines.push("// AUTO-GENERATED by scripts/gen-sqlite-vec-native.ts — DO NOT EDIT BY HAND.");
lines.push("//");
lines.push("// The committed version of this file is a STUB (BUNDLED_VEC_PATH = null).");
lines.push("// scripts/gen-sqlite-vec-native.ts overwrites it on each release-runner");
lines.push("// platform before bun build --compile, embedding that platform's vec0 lib.");
lines.push("//");
lines.push(`// Build platform: ${platform}-${arch}`);
lines.push(`// Source package: ${packageName}`);
lines.push(`// Source sha256:  ${sha}`);
lines.push("");
lines.push(`import nativePath from "${importSpec}" with { type: "file" };`);
lines.push("");
lines.push("export const BUNDLED_VEC_PATH: string | null = nativePath;");
lines.push(`export const VEC_PLATFORM_PACKAGE: string | null = ${JSON.stringify(packageName)};`);
lines.push(`export const VEC_LIB_FILENAME: string | null = ${JSON.stringify(libFilename)};`);
lines.push(`export const VEC_BUILD_PLATFORM: string | null = ${JSON.stringify(`${platform}-${arch}`)};`);
lines.push(`export const VEC_BUNDLED_SHA256: string | null = ${JSON.stringify(sha)};`);
lines.push("");

writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`wrote ${outFile}`);
console.log(`  platform: ${platform}-${arch}`);
console.log(`  package:  ${packageName}`);
console.log(`  lib:      ${libFilename}`);
console.log(`  sha256:   ${sha}`);
