// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT.
//
// To regenerate after `drizzle-kit generate` adds a new SQL file:
//   bun run db:generate     # runs drizzle-kit + this script
//   bun scripts/gen-migrations-manifest.ts   # standalone
//
// CI verifies this file matches the on-disk SQL (manifest drift check).

import sql_0 from "./migrations/0000_curved_lenny_balinger.sql" with { type: "text" };
import sql_1 from "./migrations/0001_clammy_whistler.sql" with { type: "text" };

export interface EmbeddedMigration {
  /** Stem of the SQL filename, e.g. '0000_curved_lenny_balinger'. */
  name: string;
  /** Raw SQL contents (utf-8). */
  sql: string;
  /** sha256(sql) — duplicated here so build-time + runtime hashes always agree. */
  checksum: string;
}

export const MIGRATIONS: readonly EmbeddedMigration[] = [
  { name: "0000_curved_lenny_balinger", sql: sql_0, checksum: "6ca0c3764486c465764689021dbd6e606ced3565e8dcf823244cc0ecd8a31750" },
  { name: "0001_clammy_whistler", sql: sql_1, checksum: "2c3d006caeb176b97dfaa09107beb5d8b86754044afc9635dea3b67d72001e78" },
];
