// AUTO-GENERATED by scripts/gen-sqlite-vec-native.ts — DO NOT EDIT BY HAND.
//
// Committed STUB. Real values get written by the generator on each
// release-runner platform before `bun build --compile`. When this stub
// is in place (BUNDLED_VEC_PATH === null), the runtime sqlite.ts falls
// back to sqliteVec.load() — the package's default resolver — which
// works in dev / test mode where node_modules/sqlite-vec-* is on disk.
//
// Do not import sqlite-vec-* native packages here unconditionally:
// contributors on platforms without the matching optional dep would
// fail to compile the test suite.

export const BUNDLED_VEC_PATH: string | null = null;
export const VEC_PLATFORM_PACKAGE: string | null = null;
export const VEC_LIB_FILENAME: string | null = null;
export const VEC_BUILD_PLATFORM: string | null = null;
export const VEC_BUNDLED_SHA256: string | null = null;
